// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/atvremote/proto/polo.proto

package atvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OuterMessage_Status int32

const (
	OuterMessage_STATUS_OK                OuterMessage_Status = 200
	OuterMessage_STATUS_ERROR             OuterMessage_Status = 400
	OuterMessage_STATUS_BAD_CONFIGURATION OuterMessage_Status = 401
	OuterMessage_STATUS_BAD_SECRET        OuterMessage_Status = 402
)

// Enum value maps for OuterMessage_Status.
var (
	OuterMessage_Status_name = map[int32]string{
		200: "STATUS_OK",
		400: "STATUS_ERROR",
		401: "STATUS_BAD_CONFIGURATION",
		402: "STATUS_BAD_SECRET",
	}
	OuterMessage_Status_value = map[string]int32{
		"STATUS_OK":                200,
		"STATUS_ERROR":             400,
		"STATUS_BAD_CONFIGURATION": 401,
		"STATUS_BAD_SECRET":        402,
	}
)

func (x OuterMessage_Status) Enum() *OuterMessage_Status {
	p := new(OuterMessage_Status)
	*p = x
	return p
}

func (x OuterMessage_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OuterMessage_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_atvremote_proto_polo_proto_enumTypes[0].Descriptor()
}

func (OuterMessage_Status) Type() protoreflect.EnumType {
	return &file_internal_atvremote_proto_polo_proto_enumTypes[0]
}

func (x OuterMessage_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *OuterMessage_Status) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = OuterMessage_Status(num)
	return nil
}

// Deprecated: Use OuterMessage_Status.Descriptor instead.
func (OuterMessage_Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_atvremote_proto_polo_proto_rawDescGZIP(), []int{0, 0}
}

type Options_RoleType int32

const (
	Options_ROLE_TYPE_UNKNOWN Options_RoleType = 0
	Options_ROLE_TYPE_INPUT   Options_RoleType = 1
	Options_ROLE_TYPE_OUTPUT  Options_RoleType = 2
)

// Enum value maps for Options_RoleType.
var (
	Options_RoleType_name = map[int32]string{
		0: "ROLE_TYPE_UNKNOWN",
		1: "ROLE_TYPE_INPUT",
		2: "ROLE_TYPE_OUTPUT",
	}
	Options_RoleType_value = map[string]int32{
		"ROLE_TYPE_UNKNOWN": 0,
		"ROLE_TYPE_INPUT":   1,
		"ROLE_TYPE_OUTPUT":  2,
	}
)

func (x Options_RoleType) Enum() *Options_RoleType {
	p := new(Options_RoleType)
	*p = x
	return p
}

func (x Options_RoleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Options_RoleType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_atvremote_proto_polo_proto_enumTypes[1].Descriptor()
}

func (Options_RoleType) Type() protoreflect.EnumType {
	return &file_internal_atvremote_proto_polo_proto_enumTypes[1]
}

func (x Options_RoleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Options_RoleType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Options_RoleType(num)
	return nil
}

// Deprecated: Use Options_RoleType.Descriptor instead.
func (Options_RoleType) EnumDescriptor() ([]byte, []int) {
	return file_internal_atvremote_proto_polo_proto_rawDescGZIP(), []int{3, 0}
}

type Options_Encoding_EncodingType int32

const (
	Options_Encoding_ENCODING_TYPE_UNKNOWN      Options_Encoding_EncodingType = 0
	Options_Encoding_ENCODING_TYPE_ALPHANUMERIC Options_Encoding_EncodingType = 1
	Options_Encoding_ENCODING_TYPE_NUMERIC      Options_Encoding_EncodingType = 2
	Options_Encoding_ENCODING_TYPE_HEXADECIMAL  Options_Encoding_EncodingType = 3
	Options_Encoding_ENCODING_TYPE_QRCODE       Options_Encoding_EncodingType = 4
)

// Enum value maps for Options_Encoding_EncodingType.
var (
	Options_Encoding_EncodingType_name = map[int32]string{
		0: "ENCODING_TYPE_UNKNOWN",
		1: "ENCODING_TYPE_ALPHANUMERIC",
		2: "ENCODING_TYPE_NUMERIC",
		3: "ENCODING_TYPE_HEXADECIMAL",
		4: "ENCODING_TYPE_QRCODE",
	}
	Options_Encoding_EncodingType_value = map[string]int32{
		"ENCODING_TYPE_UNKNOWN":      0,
		"ENCODING_TYPE_ALPHANUMERIC": 1,
		"ENCODING_TYPE_NUMERIC":      2,
		"ENCODING_TYPE_HEXADECIMAL":  3,
		"ENCODING_TYPE_QRCODE":       4,
	}
)

func (x Options_Encoding_EncodingType) Enum() *Options_Encoding_EncodingType {
	p := new(Options_Encoding_EncodingType)
	*p = x
	return p
}

func (x Options_Encoding_EncodingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Options_Encoding_EncodingType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_atvremote_proto_polo_proto_enumTypes[2].Descriptor()
}

func (Options_Encoding_EncodingType) Type() protoreflect.EnumType {
	return &file_internal_atvremote_proto_polo_proto_enumTypes[2]
}

func (x Options_Encoding_EncodingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Options_Encoding_EncodingType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Options_Encoding_EncodingType(num)
	return nil
}

// Deprecated: Use Options_Encoding_EncodingType.Descriptor instead.
func (Options_Encoding_EncodingType) EnumDescriptor() ([]byte, []int) {
	return file_internal_atvremote_proto_polo_proto_rawDescGZIP(), []int{3, 0, 0}
}

type OuterMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion   *uint32                `protobuf:"varint,1,req,name=protocol_version,json=protocolVersion,def=1" json:"protocol_version,omitempty"`
	Status            *OuterMessage_Status   `protobuf:"varint,2,req,name=status,enum=polo.wire.protobuf.OuterMessage_Status" json:"status,omitempty"`
	PairingRequest    *PairingRequest        `protobuf:"bytes,10,opt,name=pairing_request,json=pairingRequest" json:"pairing_request,omitempty"`
	PairingRequestAck *PairingRequestAck     `protobuf:"bytes,11,opt,name=pairing_request_ack,json=pairingRequestAck" json:"pairing_request_ack,omitempty"`
	Options           *Options               `protobuf:"bytes,20,opt,name=options" json:"options,omitempty"`
	Configuration     *Configuration         `protobuf:"bytes,30,opt,name=configuration" json:"configuration,omitempty"`
	ConfigurationAck  *ConfigurationAck      `protobuf:"bytes,31,opt,name=configuration_ack,json=configurationAck" json:"configuration_ack,omitempty"`
	Secret            *Secret                `protobuf:"bytes,40,opt,name=secret" json:"secret,omitempty"`
	SecretAck         *SecretAck             `protobuf:"bytes,41,opt,name=secret_ack,json=secretAck" json:"secret_ack,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

// Default values for OuterMessage fields.
const (
	Default_OuterMessage_ProtocolVersion = uint32(1)
)

func (x *OuterMessage) Reset() {
	*x = OuterMessage{}
	mi := &file_internal_atvremote_proto_polo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OuterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OuterMessage) ProtoMessage() {}

func (x *OuterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_atvremote_proto_polo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OuterMessage.ProtoReflect.Descriptor instead.
func (*OuterMessage) Descriptor() ([]byte, []int) {
	return file_internal_atvremote_proto_polo_proto_rawDescGZIP(), []int{0}
}

func (x *OuterMessage) GetProtocolVersion() uint32 {
	if x != nil && x.ProtocolVersion != nil {
		return *x.ProtocolVersion
	}
	return Default_OuterMessage_ProtocolVersion
}

func (x *OuterMessage) GetStatus() OuterMessage_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return OuterMessage_STATUS_OK
}

func (x *OuterMessage) GetPairingRequest() *PairingRequest {
	if x != nil {
		return x.PairingRequest
	}
	return nil
}

func (x *OuterMessage) GetPairingRequestAck() *PairingRequestAck {
	if x != nil {
		return x.PairingRequestAck
	}
	return nil
}

func (x *OuterMessage) GetOptions() *Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *OuterMessage) GetConfiguration() *Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *OuterMessage) GetConfigurationAck() *ConfigurationAck {
	if x != nil {
		return x.ConfigurationAck
	}
	return nil
}

func (x *OuterMessage) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *OuterMessage) GetSecretAck() *SecretAck {
	if x != nil {
		return x.SecretAck
	}
	return nil
}

type PairingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   *string                `protobuf:"bytes,1,req,name=service_name,json=serviceName" json:"service_name,omitempty"`
	ClientName    *string                `protobuf:"bytes,2,opt,name=client_name,json=clientName" json:"client_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairingRequest) Reset() {
	*x = PairingRequest{}
	mi := &file_internal_atvremote_proto_polo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingRequest) ProtoMessage() {}

func (x *PairingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_atvremote_proto_polo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingRequest.ProtoReflect.Descriptor instead.
func (*PairingRequest) Descriptor() ([]byte, []int) {
	return file_internal_atvremote_proto_polo_proto_rawDescGZIP(), []int{1}
}

func (x *PairingRequest) GetServiceName() string {
	if x != nil && x.ServiceName != nil {
		return *x.ServiceName
	}
	return ""
}

func (x *PairingRequest) GetClientName() string {
	if x != nil && x.ClientName != nil {
		return *x.ClientName
	}
	return ""
}

type PairingRequestAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerName    *string                `protobuf:"bytes,1,opt,name=server_name,json=serverName" json:"server_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairingRequestAck) Reset() {
	*x = PairingRequestAck{}
	mi := &file_internal_atvremote_proto_polo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingRequestAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingRequestAck) ProtoMessage() {}

func (x *PairingRequestAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_atvremote_proto_polo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingRequestAck.ProtoReflect.Descriptor instead.
func (*PairingRequestAck) Descriptor() ([]byte, []int) {
	return file_internal_atvremote_proto_polo_proto_rawDescGZIP(), []int{2}
}

func (x *PairingRequestAck) GetServerName() string {
	if x != nil && x.ServerName != nil {
		return *x.ServerName
	}
	return ""
}

type Options struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InputEncodings  []*Options_Encoding    `protobuf:"bytes,1,rep,name=input_encodings,json=inputEncodings" json:"input_encodings,omitempty"`
	OutputEncodings []*Options_Encoding    `protobuf:"bytes,2,rep,name=output_encodings,json=outputEncodings" json:"output_encodings,omitempty"`
	PreferredRole   *Options_RoleType      `protobuf:"varint,3,opt,name=preferred_role,json=preferredRole,enum=polo.wire.protobuf.Options_RoleType" json:"preferred_role,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_internal_atvremote_proto_polo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_internal_atvremote_proto_polo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_internal_atvremote_proto_polo_proto_rawDescGZIP(), []int{3}
}

func (x *Options) GetInputEncodings() []*Options_Encoding {
	if x != nil {
		return x.InputEncodings
	}
	return nil
}

func (x *Options) GetOutputEncodings() []*Options_Encoding {
	if x != nil {
		return x.OutputEncodings
	}
	return nil
}

func (x *Options) GetPreferredRole() Options_RoleType {
	if x != nil && x.PreferredRole != nil {
		return *x.PreferredRole
	}
	return Options_ROLE_TYPE_UNKNOWN
}

type Configuration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Encoding      *Options_Encoding      `protobuf:"bytes,1,req,name=encoding" json:"encoding,omitempty"`
	ClientRole    *Options_RoleType      `protobuf:"varint,2,req,name=client_role,json=clientRole,enum=polo.wire.protobuf.Options_RoleType" json:"client_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_internal_atvremote_proto_polo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_internal_atvremote_proto_polo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_internal_atvremote_proto_polo_proto_rawDescGZIP(), []int{4}
}

func (x *Configuration) GetEncoding() *Options_Encoding {
	if x != nil {
		return x.Encoding
	}
	return nil
}

func (x *Configuration) GetClientRole() Options_RoleType {
	if x != nil && x.ClientRole != nil {
		return *x.ClientRole
	}
	return Options_ROLE_TYPE_UNKNOWN
}

type ConfigurationAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationAck) Reset() {
	*x = ConfigurationAck{}
	mi := &file_internal_atvremote_proto_polo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationAck) ProtoMessage() {}

func (x *ConfigurationAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_atvremote_proto_polo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationAck.ProtoReflect.Descriptor instead.
func (*ConfigurationAck) Descriptor() ([]byte, []int) {
	return file_internal_atvremote_proto_polo_proto_rawDescGZIP(), []int{5}
}

type Secret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        []byte                 `protobuf:"bytes,1,req,name=secret" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_internal_atvremote_proto_polo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_internal_atvremote_proto_polo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_internal_atvremote_proto_polo_proto_rawDescGZIP(), []int{6}
}

func (x *Secret) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

type SecretAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        []byte                 `protobuf:"bytes,1,req,name=secret" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretAck) Reset() {
	*x = SecretAck{}
	mi := &file_internal_atvremote_proto_polo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretAck) ProtoMessage() {}

func (x *SecretAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_atvremote_proto_polo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretAck.ProtoReflect.Descriptor instead.
func (*SecretAck) Descriptor() ([]byte, []int) {
	return file_internal_atvremote_proto_polo_proto_rawDescGZIP(), []int{7}
}

func (x *SecretAck) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

type Options_Encoding struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Type          *Options_Encoding_EncodingType `protobuf:"varint,1,req,name=type,enum=polo.wire.protobuf.Options_Encoding_EncodingType" json:"type,omitempty"`
	SymbolLength  *uint32                        `protobuf:"varint,2,req,name=symbol_length,json=symbolLength" json:"symbol_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options_Encoding) Reset() {
	*x = Options_Encoding{}
	mi := &file_internal_atvremote_proto_polo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options_Encoding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options_Encoding) ProtoMessage() {}

func (x *Options_Encoding) ProtoReflect() protoreflect.Message {
	mi := &file_internal_atvremote_proto_polo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options_Encoding.ProtoReflect.Descriptor instead.
func (*Options_Encoding) Descriptor() ([]byte, []int) {
	return file_internal_atvremote_proto_polo_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Options_Encoding) GetType() Options_Encoding_EncodingType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Options_Encoding_ENCODING_TYPE_UNKNOWN
}

func (x *Options_Encoding) GetSymbolLength() uint32 {
	if x != nil && x.SymbolLength != nil {
		return *x.SymbolLength
	}
	return 0
}

var File_internal_atvremote_proto_polo_proto protoreflect.FileDescriptor

const file_internal_atvremote_proto_polo_proto_rawDesc = "" +
	"\n" +
	"#internal/atvremote/proto/polo.proto\x12\x12polo.wire.protobuf\"\xca\x05\n" +
	"\fOuterMessage\x12,\n" +
	"\x10protocol_version\x18\x01 \x02(\r:\x011R\x0fprotocolVersion\x12?\n" +
	"\x06status\x18\x02 \x02(\x0e2'.polo.wire.protobuf.OuterMessage.StatusR\x06status\x12K\n" +
	"\x0fpairing_request\x18\n" +
	" \x01(\v2\".polo.wire.protobuf.PairingRequestR\x0epairingRequest\x12U\n" +
	"\x13pairing_request_ack\x18\v \x01(\v2%.polo.wire.protobuf.PairingRequestAckR\x11pairingRequestAck\x125\n" +
	"\aoptions\x18\x14 \x01(\v2\x1b.polo.wire.protobuf.OptionsR\aoptions\x12G\n" +
	"\rconfiguration\x18\x1e \x01(\v2!.polo.wire.protobuf.ConfigurationR\rconfiguration\x12Q\n" +
	"\x11configuration_ack\x18\x1f \x01(\v2$.polo.wire.protobuf.ConfigurationAckR\x10configurationAck\x122\n" +
	"\x06secret\x18( \x01(\v2\x1a.polo.wire.protobuf.SecretR\x06secret\x12<\n" +
	"\n" +
	"secret_ack\x18) \x01(\v2\x1d.polo.wire.protobuf.SecretAckR\tsecretAck\"b\n" +
	"\x06Status\x12\x0e\n" +
	"\tSTATUS_OK\x10\xc8\x01\x12\x11\n" +
	"\fSTATUS_ERROR\x10\x90\x03\x12\x1d\n" +
	"\x18STATUS_BAD_CONFIGURATION\x10\x91\x03\x12\x16\n" +
	"\x11STATUS_BAD_SECRET\x10\x92\x03\"T\n" +
	"\x0ePairingRequest\x12!\n" +
	"\fservice_name\x18\x01 \x02(\tR\vserviceName\x12\x1f\n" +
	"\vclient_name\x18\x02 \x01(\tR\n" +
	"clientName\"4\n" +
	"\x11PairingRequestAck\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\"\xdd\x04\n" +
	"\aOptions\x12M\n" +
	"\x0finput_encodings\x18\x01 \x03(\v2$.polo.wire.protobuf.Options.EncodingR\x0einputEncodings\x12O\n" +
	"\x10output_encodings\x18\x02 \x03(\v2$.polo.wire.protobuf.Options.EncodingR\x0foutputEncodings\x12K\n" +
	"\x0epreferred_role\x18\x03 \x01(\x0e2$.polo.wire.protobuf.Options.RoleTypeR\rpreferredRole\x1a\x96\x02\n" +
	"\bEncoding\x12E\n" +
	"\x04type\x18\x01 \x02(\x0e21.polo.wire.protobuf.Options.Encoding.EncodingTypeR\x04type\x12#\n" +
	"\rsymbol_length\x18\x02 \x02(\rR\fsymbolLength\"\x9d\x01\n" +
	"\fEncodingType\x12\x19\n" +
	"\x15ENCODING_TYPE_UNKNOWN\x10\x00\x12\x1e\n" +
	"\x1aENCODING_TYPE_ALPHANUMERIC\x10\x01\x12\x19\n" +
	"\x15ENCODING_TYPE_NUMERIC\x10\x02\x12\x1d\n" +
	"\x19ENCODING_TYPE_HEXADECIMAL\x10\x03\x12\x18\n" +
	"\x14ENCODING_TYPE_QRCODE\x10\x04\"L\n" +
	"\bRoleType\x12\x15\n" +
	"\x11ROLE_TYPE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fROLE_TYPE_INPUT\x10\x01\x12\x14\n" +
	"\x10ROLE_TYPE_OUTPUT\x10\x02\"\x98\x01\n" +
	"\rConfiguration\x12@\n" +
	"\bencoding\x18\x01 \x02(\v2$.polo.wire.protobuf.Options.EncodingR\bencoding\x12E\n" +
	"\vclient_role\x18\x02 \x02(\x0e2$.polo.wire.protobuf.Options.RoleTypeR\n" +
	"clientRole\"\x12\n" +
	"\x10ConfigurationAck\" \n" +
	"\x06Secret\x12\x16\n" +
	"\x06secret\x18\x01 \x02(\fR\x06secret\"#\n" +
	"\tSecretAck\x12\x16\n" +
	"\x06secret\x18\x01 \x02(\fR\x06secretBW\n" +
	"\x1dcom.google.polo.wire.protobufB\tPoloProtoH\x03Z$shrmt/internal/atvremote/proto;atvpb"

var (
	file_internal_atvremote_proto_polo_proto_rawDescOnce sync.Once
	file_internal_atvremote_proto_polo_proto_rawDescData []byte
)

func file_internal_atvremote_proto_polo_proto_rawDescGZIP() []byte {
	file_internal_atvremote_proto_polo_proto_rawDescOnce.Do(func() {
		file_internal_atvremote_proto_polo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_atvremote_proto_polo_proto_rawDesc), len(file_internal_atvremote_proto_polo_proto_rawDesc)))
	})
	return file_internal_atvremote_proto_polo_proto_rawDescData
}

var file_internal_atvremote_proto_polo_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_atvremote_proto_polo_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_atvremote_proto_polo_proto_goTypes = []any{
	(OuterMessage_Status)(0),           // 0: polo.wire.protobuf.OuterMessage.Status
	(Options_RoleType)(0),              // 1: polo.wire.protobuf.Options.RoleType
	(Options_Encoding_EncodingType)(0), // 2: polo.wire.protobuf.Options.Encoding.EncodingType
	(*OuterMessage)(nil),               // 3: polo.wire.protobuf.OuterMessage
	(*PairingRequest)(nil),             // 4: polo.wire.protobuf.PairingRequest
	(*PairingRequestAck)(nil),          // 5: polo.wire.protobuf.PairingRequestAck
	(*Options)(nil),                    // 6: polo.wire.protobuf.Options
	(*Configuration)(nil),              // 7: polo.wire.protobuf.Configuration
	(*ConfigurationAck)(nil),           // 8: polo.wire.protobuf.ConfigurationAck
	(*Secret)(nil),                     // 9: polo.wire.protobuf.Secret
	(*SecretAck)(nil),                  // 10: polo.wire.protobuf.SecretAck
	(*Options_Encoding)(nil),           // 11: polo.wire.protobuf.Options.Encoding
}
var file_internal_atvremote_proto_polo_proto_depIdxs = []int32{
	0,  // 0: polo.wire.protobuf.OuterMessage.status:type_name -> polo.wire.protobuf.OuterMessage.Status
	4,  // 1: polo.wire.protobuf.OuterMessage.pairing_request:type_name -> polo.wire.protobuf.PairingRequest
	5,  // 2: polo.wire.protobuf.OuterMessage.pairing_request_ack:type_name -> polo.wire.protobuf.PairingRequestAck
	6,  // 3: polo.wire.protobuf.OuterMessage.options:type_name -> polo.wire.protobuf.Options
	7,  // 4: polo.wire.protobuf.OuterMessage.configuration:type_name -> polo.wire.protobuf.Configuration
	8,  // 5: polo.wire.protobuf.OuterMessage.configuration_ack:type_name -> polo.wire.protobuf.ConfigurationAck
	9,  // 6: polo.wire.protobuf.OuterMessage.secret:type_name -> polo.wire.protobuf.Secret
	10, // 7: polo.wire.protobuf.OuterMessage.secret_ack:type_name -> polo.wire.protobuf.SecretAck
	11, // 8: polo.wire.protobuf.Options.input_encodings:type_name -> polo.wire.protobuf.Options.Encoding
	11, // 9: polo.wire.protobuf.Options.output_encodings:type_name -> polo.wire.protobuf.Options.Encoding
	1,  // 10: polo.wire.protobuf.Options.preferred_role:type_name -> polo.wire.protobuf.Options.RoleType
	11, // 11: polo.wire.protobuf.Configuration.encoding:type_name -> polo.wire.protobuf.Options.Encoding
	1,  // 12: polo.wire.protobuf.Configuration.client_role:type_name -> polo.wire.protobuf.Options.RoleType
	2,  // 13: polo.wire.protobuf.Options.Encoding.type:type_name -> polo.wire.protobuf.Options.Encoding.EncodingType
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_internal_atvremote_proto_polo_proto_init() }
func file_internal_atvremote_proto_polo_proto_init() {
	if File_internal_atvremote_proto_polo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_atvremote_proto_polo_proto_rawDesc), len(file_internal_atvremote_proto_polo_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_atvremote_proto_polo_proto_goTypes,
		DependencyIndexes: file_internal_atvremote_proto_polo_proto_depIdxs,
		EnumInfos:         file_internal_atvremote_proto_polo_proto_enumTypes,
		MessageInfos:      file_internal_atvremote_proto_polo_proto_msgTypes,
	}.Build()
	File_internal_atvremote_proto_polo_proto = out.File
	file_internal_atvremote_proto_polo_proto_goTypes = nil
	file_internal_atvremote_proto_polo_proto_depIdxs = nil
}
